liftover.core <- function(in.dir, in.pattern, chain.file, out.dir, zip = T, run = T, 
                          liftOver = "/opt/apps/kentUCSC/334/liftOver") {
  dir.create(out.dir, recursive = T, showWarnings = F)
  in.vec <- list.files(in.dir) %>% .[grepl(in.pattern, .)]
  lapply(in.vec, function(x) {
    in.file <- file.path(in.dir, x)
    suffix <- chain.file %>% basename() %>% sub(".over.+", "", .) %>% sub(".to.", "_to_", .)
    ext <- tools::file_ext(x)
    root <- tools::file_path_sans_ext(x)
    out.file <- paste0(out.dir, "/", root, "_", suffix, ".", ext)
    cmd <- paste0(liftOver, " ", in.file, " ", chain.file, " ", out.file, " /dev/null")
    print(cmd)
    if (run == T) {
      system(cmd)
      if (zip == T) {
        cmd <- paste0("~/scripts/bed_browser_v2.sh ", out.file)
        print(cmd)
        system(cmd)
      }
    }
      
    
    return()
  }) 
  return()
}

liftover.multi.genomes <- function(in.bed, out.bed = NULL, ref.genome, target.genomes, minMatch = 0.95,
                                   threads = 1, 
                                  liftOver = LIFTOVER_UCSC, print.cmd = F) {
  if (!is.character(in.bed)) {
    if (! "GRanges" %in% class(in.bed)) {
      in.bed <- makeGRangesFromDataFrame(in.bed, keep.extra.columns = T)
    }
    in.bed <- utilsFanc::write.zip.fanc(df = in.bed, out.file = tempfile(), bed.shift = T, zip = F)
  }
  if (is.null(out.bed)) {
    out.bed <- tempfile()
  }
  out.unlifted <- utilsFanc::insert.name.before.ext(name = out.bed, insert = "unlifted", delim = "_")
  dir.create(dirname(out.bed), showWarnings = F, recursive = T)
  df <- utilsFanc::safelapply(target.genomes, function(target.genome) {
    lifted <- paste0(out.bed, "_", target.genome, "_lifted.bed")
    unlifted <- paste0(out.bed, "_", target.genome, "_unlifted.bed")
    chain <- paste0("~/genomes/liftover/", ref.genome, "To", 
                    utilsFanc::captilize.first.letter(target.genome), ".over.chain.gz")
    cmd <- paste0(liftOver, " -minMatch=", minMatch, " ", in.bed, " ", chain, " ", lifted, " ", unlifted)
    if (print.cmd)
      print(cmd)
    system(cmd)
    lifted.df <- utilsFanc::import.bed.fanc(lifted) %>% dplyr::mutate(genome = target.genome)
    # browser()
    if (file.size(unlifted) > 0 )
      unlifted.df <- utilsFanc::import.bed.fanc(unlifted) %>% dplyr::mutate(genome = "unlifted")
    else
      unlifted.df <- data.frame()
    return(rbind(lifted.df, unlifted.df))
  }, threads = threads) %>% Reduce(rbind, .)
  lifted <- df %>% dplyr::filter(genome != "unlifted")
  unlifted <- df %>% dplyr::filter(genome == "unlifted")
  utilsFanc::write.zip.fanc(df = lifted, out.file = out.bed, bed.shift = T, zip = F)
  trash <- utilsFanc::write.zip.fanc(df = unlifted, out.file = out.unlifted, bed.shift = T, zip = T)
  return(lifted)
}

fa.simple.liftOver <- function(in.gr, ori.fa, direction) {
  # take advantage of the maps between original sequences and noRepeat sequences
  #generated by fa.remove.repeat.
  # direction: either "shrink" or "expand"
  if (is.data.frame(in.gr)) {
    in.gr <- makeGRangesFromDataFrame(in.gr, keep.extra.columns = T)
  }
  lifted <- lapply(1:length(in.gr), function(i) {
    r <- in.gr[i]
    map <- paste0(ori.fa, "_map/", as.character(seqnames(r)), "_map.tsv")
    map <- read.table(map, header = T)
    if (direction == "shrink") {
      col.name <- "ori.pos"
      col.name.lifted <- "noRepeat.pos"
    } else if (direction == "expand") {
      col.name <- "noRepeat.pos"
      col.name.lifted <- "ori.pos"
    } else {
      stop("direction has to be shrink or expand")
    }
    df <- data.frame(V = start(r):end(r))  
    colnames(df) <- col.name
    mapped <- left_join(df, map) %>% na.omit()
    lifted <- mapped[, col.name.lifted]
    out <- data.frame(chr = seqnames(r) %>% as.character(),
                      start = min(lifted), end = max(lifted))
    return(out)
  }) %>% Reduce(rbind, .) %>% makeGRangesFromDataFrame(keep.extra.columns = T)
  return(lifted)
}

loci.fast.shift <- function(loci1, loci2, new.chr = NULL, return.loci = T) {
  if (is.character(loci1)) {
    loci1 <- utilsFanc::loci.2.gr(loci1)
  }
  if (is.character(loci2)) {
    loci2 <- utilsFanc::loci.2.gr(loci2)
  }
  out <- data.frame(chr = seqnames(loci1) %>% as.character(),  
                    start = start(loci2) - start(loci1) + 1,
                    end = end(loci2) - start(loci1) + 1)
  if (!is.null(new.chr)) {
    out$chr <- new.chr
  }
  if (return.loci) {
    out <- paste0(out$chr, ":",  out$start, "-", out$end)
  } else {
    out <- makeGRangesFromDataFrame(df = out)
  }
  return(out)
}

